judge:
  host: http://arena.maycamp.com
  root: ../../sandbox
  user: maycamp
valo:
  host: http://localhost:3000
  root: /tmp
  user: valentinmihov
grader:
  host: http://localhost:3000
  root: /home/spoj0run
  user: spoj0run
